import { Sparkles } from 'lucide-react';

export function AIExplanationCard({ explanation }: { explanation: string }) {
  return (
    <div className="relative p-[1px] rounded-xl bg-gradient-to-br from-amber-500/20 via-transparent to-amber-500/10 mt-6">
      <div className="bg-[#09090b]/90 backdrop-blur-md rounded-xl p-4 flex flex-col gap-3">
        <div className="flex items-center gap-2 text-amber-500">
          <Sparkles className="w-4 h-4" />
          <span className="text-xs font-semibold tracking-wider uppercase">Generated by Groq · Llama</span>
        </div>
        <p className="text-sm text-zinc-300 italic leading-relaxed">
          &ldquo;{explanation}&rdquo;
        </p>
      </div>
    </div>
  );
}
